### ISSUE TITLE
Update requirements and test matrix, use Github workflow

### ISSUE THREAD

**Issue by Bartvaderkin** [maykinmedia/mail-editor#29]
I note the requirements and test matrix are pretty outdated with Python 2.7-3.5, Django 1.10.

So no Django 2.2 LTS, 3.2 LTS or 4.x, nor the recent Pythons we use this with in production.

Also this uses Travis CI? Probably should update to Github workflows?

**Comment by alextreme** [comment]
Feel free to expand the test matrix and update the requirements. I think Anna did an attempt early last year: https://github.com/maykinmedia/mail-editor/tree/feature/support-django3 and Sonny did so in 2021: https://github.com/maykinmedia/mail-editor/tree/update-django
