### ISSUE TITLE
Removal of npm packages + script for generating HTML-emails

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/mail-editor#30]
Using a small JS script and npm dependancies for generating HTML emails was always a bit of a hack.

If we have time I'd like to see if now (6 years later) we can clean this up and use python for generating the HTML in the sent emails. This to avoid the complexity of a frontend-toolchain for a backend process/django-app.

**Comment by sergei-maertens** [comment]
Adding to this that I am very much looking for a solution that also supports design tokens (or at least style-dictionary), preferably even with external stylesheets (but raw input JSON would also work).

**Comment by sergei-maertens** [comment]
https://pypi.org/project/css-inline/ looks like a proper replacement
